server:
  port: 8080
  #context-path: /market
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 192.168.2.129
    port: 6379
    #password: 123456
    #jedis:
    #  pool:
    #    max-active: 8
    #    max-wait: 1
    #    max-idle: 8
    #    min-idle: 0
    #timeout: 0
  mvc:
    static-path-pattern:  /**
  freemarker:
    request-context-attribute: req #req访问request
    suffix: .ftl #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##' #数字格式化，无小数点
      classic_compatible: true  #处理空值为空字符串
      auto_import: 'common/lib/index.ftl as m' #导入自定义内容
  # 默认值为 classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  resources:
    static-locations: classpath:/static/

    #jsp配置
    #view:
    #prefix: /
    #suffix: .jsp
  datasource:
    db1:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.2.129:3306/xcard?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
      #driver-class-name: com.mysql.jdbc.Driver  #mysql5
      driver-class-name: com.mysql.cj.jdbc.Driver   #mysql8
      #db2:
      #type: com.alibaba.druid.pool.DruidDataSource
      #url: jdbc:mysql://192.168.1.12:3306/xcard1?characterEncoding=UTF-8
      #username: root
      #password: root
      #driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: com.xyh.game.CustomMysqlDialect
  rabbitmq:
    host: 192.168.2.129
    port: 5672
    username: admin
    password: admin
    virtual-host: my_vhost

mybatis-plus:
  typeAliasesPackage: com.xyh.game.mybatisplus.entity
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:dao/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  host: 192.168.2.129
  port: 9200
  username: elastic
  password: changeme
